### ISSUE TITLE
Update README.MD for a more accurate explanation as to how to run a local instance of Augur

### ISSUE THREAD

**Issue by snewell-WS** [Simon-SS/augur_view_group_12#5]
The current README.md that we are using has a outdated explanation of how to set up a local instance of Augur. I would recommend  changing the file so that it matches with what the README.md says on https://github.com/augurlabs/augur_view or replacing it with the one that https://github.com/augurlabs/augur_view uses

**Comment by Simon-SS** [comment]
I made all our feature branches from https://github.com/Simon-SS/augur_view_group_12/tree/dev , which has the right README. See the about page branch here: https://github.com/Simon-SS/augur_view_group_12/tree/about-page-feature
